export const config: Config = {
  physicsAccuracy: 3,
  mouseInfluence: 20,
  mouseCut: 2,
  gravity: 1200,
  clothHeight: 60,
  clothWidth: 100,
  startY: 20,
  spacing: 7,
  tearDistance: 60,
  canvas: null,
  ctx: null,
  cloth: null,
  boundsx: null,
  boundsy: null,
  mouse: {
    down: false,
    button: 1,
    x: 0,
    y: 0,
    px: 0,
    py: 0,
  },
}
